module VerifyExamples.Handlebars.Syntax.Exp0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Syntax exposing (..)
import Result.Extra as Result
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser







spec0 : Test.Test
spec0 =
    Test.test "#exp: \n\n    \"{{test}}\"\n    |> Parser.run exp\n    --> Ok (Variable (LookUp (0,[\"test\"])))" <|
        \() ->
            Expect.equal
                (
                "{{test}}"
                |> Parser.run exp
                )
                (
                Ok (Variable (LookUp (0,["test"])))
                )