module VerifyExamples.Handlebars.Syntax.Exp12 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Syntax exposing (..)
import Result.Extra as Result
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser







spec12 : Test.Test
spec12 =
    Test.test "#exp: \n\n    \"Hello \\\\{\\\\{world\\\\}\\\\}\"\n    |> Parser.run exp\n    --> Ok (Text \"Hello {{world}}\")" <|
        \() ->
            Expect.equal
                (
                "Hello \\{\\{world\\}\\}"
                |> Parser.run exp
                )
                (
                Ok (Text "Hello {{world}}")
                )