module VerifyExamples.Handlebars.Syntax.Exp1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Syntax exposing (..)
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser







spec1 : Test.Test
spec1 =
    Test.test "#exp: \n\n    \"{{test}}\"\n    |> Parser.run exp\n    --> Ok (Variable (LookUp [Just \"test\"]))" <|
        \() ->
            Expect.equal
                (
                "{{test}}"
                |> Parser.run exp
                )
                (
                Ok (Variable (LookUp [Just "test"]))
                )