module VerifyExamples.Handlebars.Syntax.Exp2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Syntax exposing (..)
import Result.Extra as Result
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser







spec2 : Test.Test
spec2 =
    Test.test "#exp: \n\n    \"{{#blockHelper (helper a)}}hello world{{/blockHelper}}\"\n    |> Parser.run exp\n    --> Ok (Block \"blockHelper\" (Helper \"helper\" (LookUp (0,[\"a\"]),[])) [Text \"hello world\"])" <|
        \() ->
            Expect.equal
                (
                "{{#blockHelper (helper a)}}hello world{{/blockHelper}}"
                |> Parser.run exp
                )
                (
                Ok (Block "blockHelper" (Helper "helper" (LookUp (0,["a"]),[])) [Text "hello world"])
                )