module VerifyExamples.Handlebars.Syntax.Exp4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Syntax exposing (..)
import Result.Extra as Result
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser







spec4 : Test.Test
spec4 =
    Test.test "#exp: \n\n    \"{{#.invalid.}}hello world{{/.invalid.}}\"\n    |> Parser.run exp\n    |> Result.isOk\n    --> False" <|
        \() ->
            Expect.equal
                (
                "{{#.invalid.}}hello world{{/.invalid.}}"
                |> Parser.run exp
                |> Result.isOk
                )
                (
                False
                )