module VerifyExamples.Handlebars.Syntax.Exp4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Syntax exposing (..)
import Result.Extra as Result
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser







spec4 : Test.Test
spec4 =
    Test.test "#exp: \n\n    \"{{#test a}}hello world{{/test}}\"\n    |> Parser.run exp\n    --> Ok (Block \"test\" (LookUp (0,[\"a\"])) (Text \"hello world\"))" <|
        \() ->
            Expect.equal
                (
                "{{#test a}}hello world{{/test}}"
                |> Parser.run exp
                )
                (
                Ok (Block "test" (LookUp (0,["a"])) (Text "hello world"))
                )