module VerifyExamples.Handlebars.Syntax.Exp7 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Syntax exposing (..)
import Result.Extra as Result
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser







spec7 : Test.Test
spec7 =
    Test.test "#exp: \n\n    \"{{#test}}hello world{{/test}}\"\n        |> Parser.run exp\n    --> Ok (For (0,[\"test\"]) [Text \"hello world\"])" <|
        \() ->
            Expect.equal
                (
                "{{#test}}hello world{{/test}}"
                    |> Parser.run exp
                )
                (
                Ok (For (0,["test"]) [Text "hello world"])
                )