module VerifyExamples.Handlebars.Syntax.Path0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Syntax exposing (..)
import Result.Extra as Result
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser







spec0 : Test.Test
spec0 =
    Test.test "#path: \n\n    \"some.test a\"\n    |> Parser.run path\n    --> Ok (0,[\"some\", \"test\"])" <|
        \() ->
            Expect.equal
                (
                "some.test a"
                |> Parser.run path
                )
                (
                Ok (0,["some", "test"])
                )