module VerifyExamples.Handlebars.Syntax.Path1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Syntax exposing (..)
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser







spec1 : Test.Test
spec1 =
    Test.test "#path: \n\n    \"\"\n    |> Parser.run path\n    |> (\\err ->\n        case err of\n            Err _ ->\n                False\n            Ok _ ->\n                True\n        )\n    --> False" <|
        \() ->
            Expect.equal
                (
                ""
                |> Parser.run path
                |> (\err ->
                    case err of
                        Err _ ->
                            False
                        Ok _ ->
                            True
                    )
                )
                (
                False
                )