module VerifyExamples.Handlebars.Syntax.Path1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Syntax exposing (..)
import Result.Extra as Result
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser







spec1 : Test.Test
spec1 =
    Test.test "#path: \n\n    \"../some\"\n    |> Parser.run path\n    --> Ok (1,[\"some\"])" <|
        \() ->
            Expect.equal
                (
                "../some"
                |> Parser.run path
                )
                (
                Ok (1,["some"])
                )