module VerifyExamples.Handlebars.Syntax.SubExp0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Syntax exposing (..)
import Result.Extra as Result
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser







spec0 : Test.Test
spec0 =
    Test.test "#subExp: \n\n    \"some (a)\"\n    |> Parser.run subExp\n    --> Ok (Helper \"some\" (LookUp (0,[\"a\"]),[]))" <|
        \() ->
            Expect.equal
                (
                "some (a)"
                |> Parser.run subExp
                )
                (
                Ok (Helper "some" (LookUp (0,["a"]),[]))
                )