module VerifyExamples.Handlebars.Syntax.SubExp4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Syntax exposing (..)
import Result.Extra as Result
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser







spec4 : Test.Test
spec4 =
    Test.test "#subExp: \n\n    \"test a b c\"\n    |> Parser.run subExp\n    --> Ok (Helper \"test\" (LookUp (0,[\"a\"]),[LookUp (0,[\"b\"]),LookUp (0,[\"c\"])]))" <|
        \() ->
            Expect.equal
                (
                "test a b c"
                |> Parser.run subExp
                )
                (
                Ok (Helper "test" (LookUp (0,["a"]),[LookUp (0,["b"]),LookUp (0,["c"])]))
                )