module VerifyExamples.Handlebars.Value.Get0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Value exposing (..)
import Array
import Dict



isValid : Value
isValid =
    BooleanValue True
array : Value
array =
    [ jack, gill ]
    |> Array.fromList
    |> ArrayValue
gill : Value
gill = StringValue "Gill"
jack : Value
jack = StringValue "Jack"
object : Value
object = Dict.fromList [ ( "name", StringValue "Jack" ) ] |> ObjectValue



spec0 : Test.Test
spec0 =
    Test.test "#get: \n\n    isValid\n        |> get []\n    --> Just isValid" <|
        \() ->
            Expect.equal
                (
                isValid
                    |> get []
                )
                (
                Just isValid
                )