module VerifyExamples.Handlebars.Value.Get13 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Value exposing (..)
import Array
import Dict



array : Value
array =
    [ jack, gill ]
    |> Array.fromList
    |> ArrayValue
gill : Value
gill = StringValue "Gill"
jack : Value
jack = StringValue "Jack"
object : Value
object = Dict.fromList [ ( "name", StringValue "Jack" ) ] |> ObjectValue



spec13 : Test.Test
spec13 =
    Test.test "#get: \n\n    array\n        |> get []\n    --> Just array" <|
        \() ->
            Expect.equal
                (
                array
                    |> get []
                )
                (
                Just array
                )