module VerifyExamples.Handlebars.Value.Get16 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Value exposing (..)
import Array
import Dict



array : Value
array =
    [ jack, gill ]
    |> Array.fromList
    |> ArrayValue
gill : Value
gill = StringValue "Gill"
jack : Value
jack = StringValue "Jack"
object : Value
object = Dict.fromList [ ( "name", StringValue "Jack" ) ] |> ObjectValue



spec16 : Test.Test
spec16 =
    Test.test "#get: \n\n    [ ( \"name\"\n      , [ ( \"@key\", StringValue \"impossible State\" ) ] |> Dict.fromList |> ObjectValue\n      )\n    ]\n        |> Dict.fromList\n        |> ObjectValue\n        |> get [ \"name\", \"@key\" ]\n    --> Just (StringValue \"name\")" <|
        \() ->
            Expect.equal
                (
                [ ( "name"
                  , [ ( "@key", StringValue "impossible State" ) ] |> Dict.fromList |> ObjectValue
                  )
                ]
                    |> Dict.fromList
                    |> ObjectValue
                    |> get [ "name", "@key" ]
                )
                (
                Just (StringValue "name")
                )