module VerifyExamples.Handlebars.Value.Get7 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Value exposing (..)
import Array
import Dict



array : Value
array =
    [ jack, gill ]
    |> Array.fromList
    |> ArrayValue
gill : Value
gill = StringValue "Gill"
jack : Value
jack = StringValue "Jack"
object : Value
object = Dict.fromList [ ( "name", StringValue "Jack" ) ] |> ObjectValue



spec7 : Test.Test
spec7 =
    Test.test "#get: \n\n    array\n        |> get [\"1\",\"@index\"]\n    --> Just (StringValue \"1\")" <|
        \() ->
            Expect.equal
                (
                array
                    |> get ["1","@index"]
                )
                (
                Just (StringValue "1")
                )