module VerifyExamples.Internal.Path.RelativeToString1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Internal.Path exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#relativeToString: \n\n    (0,[\"a\", \"b\"])\n        |> relativeToString\n    --> \"a.b\"" <|
        \() ->
            Expect.equal
                (
                (0,["a", "b"])
                    |> relativeToString
                )
                (
                "a.b"
                )