module VerifyExamples.Internal.Path.RelativeToString5 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Handlebars.Path exposing (..)
import Test


spec5 : Test.Test
spec5 =
    Test.test "#relativeToString: \n\n    (0,[\"a\"])\n        |> relativeToString\n    --> \"a\"" <|
        \() ->
            Expect.equal
                (( 0, [ "a" ] )
                    |> relativeToString
                )
                "a"
