module VerifyExamples.Internal.Path.RelativeToString3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Expect
import Handlebars.Path exposing (..)
import Test


spec3 : Test.Test
spec3 =
    Test.test "#relativeToString: \n\n    (1,[\"a\"])\n        |> relativeToString\n    --> \"../a\"" <|
        \() ->
            Expect.equal
                (( 1, [ "a" ] )
                    |> relativeToString
                )
                "../a"
