module VerifyExamples.Internal.Path.WithRelativePath2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Internal.Path exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#withRelativePath: \n\n    [ \"people\",\"jack\"]\n        |> withRelativePath [Nothing, Just \"gill\"]\n    --> Just [\"people\",\"gill\"]" <|
        \() ->
            Expect.equal
                (
                [ "people","jack"]
                    |> withRelativePath [Nothing, Just "gill"]
                )
                (
                Just ["people","gill"]
                )