module VerifyExamples.Internal.Path.WithRelativePath4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Internal.Path exposing (..)







spec4 : Test.Test
spec4 =
    Test.test "#withRelativePath: \n\n    [ \"people\", \"jack\"]\n        |> withRelativePath (-1,[])\n    --> Nothing" <|
        \() ->
            Expect.equal
                (
                [ "people", "jack"]
                    |> withRelativePath (-1,[])
                )
                (
                Nothing
                )