module VerifyExamples.Internal.Path.WithRelativePath1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Internal.Path exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#withRelativePath: \n\n    [ \"people\",\"jack\" ]\n        |> withRelativePath [ Nothing, Nothing, Just \"cities\" ]\n    --> Just [ \"cities\"]" <|
        \() ->
            Expect.equal
                (
                [ "people","jack" ]
                    |> withRelativePath [ Nothing, Nothing, Just "cities" ]
                )
                (
                Just [ "cities"]
                )