module VerifyExamples.Internal.Path.WithRelativePath0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Internal.Path exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#withRelativePath: \n\n    [ \"people\",\"jack\"]\n        |> withRelativePath [Nothing,Nothing,Nothing]\n    --> Nothing" <|
        \() ->
            Expect.equal
                (
                [ "people","jack"]
                    |> withRelativePath [Nothing,Nothing,Nothing]
                )
                (
                Nothing
                )