module VerifyExamples.Handlebars.Path.RelativeToString2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Path exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#relativeToString: \n\n    (2,[])\n        |> relativeToString\n    --> \"../../.\"" <|
        \() ->
            Expect.equal
                (
                (2,[])
                    |> relativeToString
                )
                (
                "../../."
                )