module VerifyExamples.Handlebars.Path.RelativeToString0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Path exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#relativeToString: \n\n    (1,[\"a\", \"b\"])\n        |> relativeToString\n    --> \"../a.b\"" <|
        \() ->
            Expect.equal
                (
                (1,["a", "b"])
                    |> relativeToString
                )
                (
                "../a.b"
                )