module VerifyExamples.Handlebars.Path.RelativeToString4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Path exposing (..)







spec4 : Test.Test
spec4 =
    Test.test "#relativeToString: \n\n    (-1,[\"a\"])\n        |> relativeToString\n    --> \"a\"" <|
        \() ->
            Expect.equal
                (
                (-1,["a"])
                    |> relativeToString
                )
                (
                "a"
                )