module VerifyExamples.Handlebars.Path.ToString0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Path exposing (..)



list : List String
list =
    ["people","Jack"]



spec0 : Test.Test
spec0 =
    Test.test "#toString: \n\n    list\n        |> toString\n    --> relativeToString (0,list)" <|
        \() ->
            Expect.equal
                (
                list
                    |> toString
                )
                (
                relativeToString (0,list)
                )