module VerifyExamples.Handlebars.Path.WithRelativePath0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Path exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#withRelativePath: \n\n    [ \"people\",\"jack\"]\n        |> withRelativePath (3,[])\n    --> Nothing" <|
        \() ->
            Expect.equal
                (
                [ "people","jack"]
                    |> withRelativePath (3,[])
                )
                (
                Nothing
                )