module VerifyExamples.Handlebars.Path.WithRelativePath1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Path exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#withRelativePath: \n\n    [ \"people\",\"jack\" ]\n        |> withRelativePath (2,[ \"cities\" ])\n    --> Just [ \"cities\"]" <|
        \() ->
            Expect.equal
                (
                [ "people","jack" ]
                    |> withRelativePath (2,[ "cities" ])
                )
                (
                Just [ "cities"]
                )