module VerifyExamples.Handlebars.Path.WithRelativePath3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Path exposing (..)







spec3 : Test.Test
spec3 =
    Test.test "#withRelativePath: \n\n    [ \"people\", \"jack\"]\n        |> withRelativePath (0,[])\n    --> Just [\"people\",\"jack\"]" <|
        \() ->
            Expect.equal
                (
                [ "people", "jack"]
                    |> withRelativePath (0,[])
                )
                (
                Just ["people","jack"]
                )