module VerifyExamples.Handlebars.Type.Normalize0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Type exposing (..)
import Dict







spec0 : Test.Test
spec0 =
    Test.test "#normalize: \n\n    [ ([\"people\"],Just ())]\n        |> Dict.fromList\n        |> normalize\n    --> Just ([(\"people\",Just Any)] |> Dict.fromList |> DictType)" <|
        \() ->
            Expect.equal
                (
                [ (["people"],Just ())]
                    |> Dict.fromList
                    |> normalize
                )
                (
                Just ([("people",Just Any)] |> Dict.fromList |> DictType)
                )