module VerifyExamples.Handlebars.Type.Normalize1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Type exposing (..)
import Dict







spec1 : Test.Test
spec1 =
    Test.test "#normalize: \n\n    [ ([\"@index\"],Nothing)]\n        |> Dict.fromList\n        |> normalize\n    --> Just (ArrayType Nothing)" <|
        \() ->
            Expect.equal
                (
                [ (["@index"],Nothing)]
                    |> Dict.fromList
                    |> normalize
                )
                (
                Just (ArrayType Nothing)
                )