module VerifyExamples.Handlebars.Type.Normalize2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Type exposing (..)
import Dict







spec2 : Test.Test
spec2 =
    Test.test "#normalize: \n\n    [ ([],Just ())]\n        |> Dict.fromList\n        |> normalize\n    --> Just Any" <|
        \() ->
            Expect.equal
                (
                [ ([],Just ())]
                    |> Dict.fromList
                    |> normalize
                )
                (
                Just Any
                )