module VerifyExamples.Handlebars.Type.Normalize3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Type exposing (..)
import Dict







spec3 : Test.Test
spec3 =
    Test.test "#normalize: \n\n    [ ([],Nothing)]\n        |> Dict.fromList\n        |> normalize\n    --> Nothing" <|
        \() ->
            Expect.equal
                (
                [ ([],Nothing)]
                    |> Dict.fromList
                    |> normalize
                )
                (
                Nothing
                )