module VerifyExamples.Handlebars.Type.Normalize4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Type exposing (..)
import Dict







spec4 : Test.Test
spec4 =
    Test.test "#normalize: \n\n    []\n        |> Dict.fromList\n        |> normalize\n    --> Nothing" <|
        \() ->
            Expect.equal
                (
                []
                    |> Dict.fromList
                    |> normalize
                )
                (
                Nothing
                )