module VerifyExamples.Handlebars.Helper.Inside0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Helper exposing (..)
import Json.Decode as D
import Handlebars
import Result.Extra as Result
import Handlebars exposing (Error(..))
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser



compile : String -> String -> Maybe (Result Error String)
compile template value =
    case value |> D.decodeString D.value of
        Ok v ->
            v
            |> Handlebars.compile Handlebars.defaultConfig
                template
            |> Just
        Err _ -> Nothing



spec0 : Test.Test
spec0 =
    Test.test "#inside: \n\n    \"{ \\\"name\\\":\\\"Jack\\\",\\\"key\\\":\\\"name\\\" }\"\n        |> compile \"{{#inside key}}{{.}}{{/inside}}\"\n    --> Just (Ok \"Jack\")" <|
        \() ->
            Expect.equal
                (
                "{ \"name\":\"Jack\",\"key\":\"name\" }"
                    |> compile "{{#inside key}}{{.}}{{/inside}}"
                )
                (
                Just (Ok "Jack")
                )