module VerifyExamples.Handlebars.Helper.Inside2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Helper exposing (..)
import Json.Decode as D
import Result.Extra as Result
import Handlebars exposing (Error(..))
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser



compile : String -> String -> Maybe String
compile template value =
    case value |> D.decodeString D.value of
        Ok v ->
            case
                v
                |> Handlebars.compile Handlebars.defaultConfig
                    template
            of
            Ok result -> Just result
            Err _ -> Nothing
        Err _ -> Nothing



spec2 : Test.Test
spec2 =
    Test.test "#inside: \n\n    \"{ \\\"name\\\":\\\"Jack\\\",\\\"key\\\":\\\"name\\\" }\"\n        |> compile \"{{#inside key}}{{.}}{{/inside}}\"\n    --> Just (\"Jack\")" <|
        \() ->
            Expect.equal
                (
                "{ \"name\":\"Jack\",\"key\":\"name\" }"
                    |> compile "{{#inside key}}{{.}}{{/inside}}"
                )
                (
                Just ("Jack")
                )