module VerifyExamples.Handlebars.Expression.EvalExp10 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Expression exposing (..)
import Array
import Handlebars
import Handlebars.Value exposing (Value(..))
import Dict



value : Value
value =
    [ ( "name", jack )
    , ( "key", StringValue "name" )
    , ( "valid", BooleanValue True)
    , ( "people",
        [ StringValue "jack" , StringValue "gill" ]
        |> Array.fromList
        |> ArrayValue
    )
    ]
        |> Dict.fromList
        |> ObjectValue
jack : Value
jack =
    StringValue "jack"



spec10 : Test.Test
spec10 =
    Test.test "#evalExp: \n\n    evalExp Handlebars.defaultConfig\n        (\"Hello World\"\n            |> Text\n        )\n        value\n    --> Ok \"Hello World\"" <|
        \() ->
            Expect.equal
                (
                evalExp Handlebars.defaultConfig
                    ("Hello World"
                        |> Text
                    )
                    value
                )
                (
                Ok "Hello World"
                )