module VerifyExamples.Handlebars.Expression.EvalSubExp4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Expression exposing (..)
import Handlebars.Value exposing (Value(..))
import Handlebars exposing (defaultConfig)
import Dict



value : Value
value =
    [ ( "name", jack )
    , ( "key", StringValue "name" )
    ]
        |> Dict.fromList
        |> ObjectValue
jack : Value
jack =
    StringValue "jack"



spec4 : Test.Test
spec4 =
    Test.test "#evalSubExp: \n\n    LookUp [Nothing]\n        |> evalSubExp defaultConfig value\n    --> Err (PathNotValid [] [Nothing])" <|
        \() ->
            Expect.equal
                (
                LookUp [Nothing]
                    |> evalSubExp defaultConfig value
                )
                (
                Err (PathNotValid [] [Nothing])
                )