module VerifyExamples.Handlebars.Expression.EvalSubExp0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Expression exposing (..)
import Handlebars.Value exposing (Value(..))
import Handlebars exposing (defaultConfig)
import Dict



value : Value
value =
    [ ( "name", jack )
    , ( "key", StringValue "name" )
    ]
        |> Dict.fromList
        |> ObjectValue
jack : Value
jack =
    StringValue "jack"



spec0 : Test.Test
spec0 =
    Test.test "#evalSubExp: \n\n    Helper \"invalid\" (LookUp (0,[]),[])\n        |> evalSubExp defaultConfig value\n        |> (\\err ->\n            case err of\n                Err (HelperNotFound _) ->\n                    False\n                _ ->\n                    True\n        )\n    --> False" <|
        \() ->
            Expect.equal
                (
                Helper "invalid" (LookUp (0,[]),[])
                    |> evalSubExp defaultConfig value
                    |> (\err ->
                        case err of
                            Err (HelperNotFound _) ->
                                False
                            _ ->
                                True
                    )
                )
                (
                False
                )