module VerifyExamples.Handlebars.Expression.EvalExp1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Expression exposing (..)
import Array
import Handlebars
import Handlebars.Value exposing (Value(..))
import Dict



value : Value
value =
    [ ( "name", jack )
    , ( "key", StringValue "name" )
    , ( "valid", BooleanValue True)
    , ( "people",
        [ StringValue "jack" , StringValue "gill" ]
        |> Array.fromList
        |> ArrayValue
    )
    ]
        |> Dict.fromList
        |> ObjectValue
jack : Value
jack =
    StringValue "jack"



spec1 : Test.Test
spec1 =
    Test.test "#evalExp: \n\n    evalExp Handlebars.defaultConfig\n        ( Block \"if\" (LookUp (0,[\"valid\"]))\n            (Text \"Hello\")\n        )\n        value\n    --> Ok \"Hello\"" <|
        \() ->
            Expect.equal
                (
                evalExp Handlebars.defaultConfig
                    ( Block "if" (LookUp (0,["valid"]))
                        (Text "Hello")
                    )
                    value
                )
                (
                Ok "Hello"
                )