module VerifyExamples.Handlebars.Expression.EvalExp3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Expression exposing (..)
import Array
import Handlebars
import Handlebars.Value exposing (Value(..))
import Dict



value : Value
value =
    [ ( "name", jack )
    , ( "key", StringValue "name" )
    , ( "valid", BooleanValue True)
    , ( "people",
        [ StringValue "jack" , StringValue "gill" ]
        |> Array.fromList
        |> ArrayValue
    )
    ]
        |> Dict.fromList
        |> ObjectValue
jack : Value
jack =
    StringValue "jack"



spec3 : Test.Test
spec3 =
    Test.test "#evalExp: \n\n    evalExp Handlebars.defaultConfig\n        ( For (42,[])\n            [\"Success\" |> Text]\n        )\n        value\n        |> (\\err ->\n            case err of\n                Err (PathNotValid _ _) ->\n                    False\n                _ ->\n                    True\n            )\n    --> False" <|
        \() ->
            Expect.equal
                (
                evalExp Handlebars.defaultConfig
                    ( For (42,[])
                        ["Success" |> Text]
                    )
                    value
                    |> (\err ->
                        case err of
                            Err (PathNotValid _ _) ->
                                False
                            _ ->
                                True
                        )
                )
                (
                False
                )