module VerifyExamples.Handlebars.Expression.EvalExp0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars.Expression exposing (..)
import Array
import Handlebars
import Handlebars.Value exposing (Value(..))
import Dict



value : Value
value =
    [ ( "name", jack )
    , ( "key", StringValue "name" )
    , ( "valid", BooleanValue True)
    , ( "people",
        [ StringValue "jack" , StringValue "gill" ]
        |> Array.fromList
        |> ArrayValue
    )
    ]
        |> Dict.fromList
        |> ObjectValue
jack : Value
jack =
    StringValue "jack"



spec0 : Test.Test
spec0 =
    Test.test "#evalExp: \n\n    evalExp Handlebars.defaultConfig\n        ( Block \"invalid\" (LookUp (0,[]))\n            [Text \"Hello\"]\n        )\n        value\n    --> Err (BlockHelperNotFound \"invalid\")" <|
        \() ->
            Expect.equal
                (
                evalExp Handlebars.defaultConfig
                    ( Block "invalid" (LookUp (0,[]))
                        [Text "Hello"]
                    )
                    value
                )
                (
                Err (BlockHelperNotFound "invalid")
                )