module VerifyExamples.Handlebars.Compile0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Handlebars exposing (..)
import Json.Decode as D
import Handlebars
import Result.Extra as Result
import Handlebars.Expression as Expression exposing (Expression(..), SubExp(..))
import Parser



compile : String -> String -> (Result Error String)
compile  template value =
    case value |> D.decodeString D.value of
        Ok v ->
            v
                |> Handlebars.compile Handlebars.defaultConfig
                    template
        Err err -> Ok (D.errorToString err)



spec0 : Test.Test
spec0 =
    Test.test "#compile: \n\n    \"{ \\\"valid\\\":true }\"\n        |> compile \"Hello There\"\n    --> (Ok \"Hello There\")" <|
        \() ->
            Expect.equal
                (
                "{ \"valid\":true }"
                    |> compile "Hello There"
                )
                (
                (Ok "Hello There")
                )